---
title: "Cough Project Main File"
author: "Raphael Kroes"
date: "2023-12-07"
output: html_document
---


```{r}
### activate packages and read in hyperparameters at the start of EVERY session
library(readxl)
library(dplyr)
library(parallel)
library(lubridate)
library(ggplot2)
library(writexl)

real.data<- TRUE
cutoff_quantile<- 0.95
selected.max.length.of.episode<- 21
```

```{r}
# Initialisation. Alternatively, load the corresponding .RData-file
source("https://raw.githubusercontent.com/rapkroes/Code_UKSH_Husten/refs/heads/main/initialisation.R")
save.image("cough_project_workspace.RData")
```
```{r}
t1_r1<- summary.stats(episodedf = full_r1)
t1_r2<- summary.stats(episodedf = full_r2)
write.table(t1_r1, "table1_r1.csv", sep = "; ")
write.table(t1_r2, "table1_r2.csv", sep = "; ")
```



```{r}
# analyses regarding diagnoses
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = c(2000, 2019), 
               dependent.variable = "diag",  research.question = 
                 "Welche Diagnosen wurden zuerst gestellt, 2000-2019, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = c(2000, 2019), 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt, 2000-2019, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = FALSE, AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt, ohne Pandemie R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = FALSE, AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt, ohne Pandemie R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "An wie vielen Besuchen wurden Diagnosen gestellt, R1",
               diag_initial_last = "first", diag_no_diagnoses = TRUE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "An wie vielen Besuchen wurden Diagnosen gestellt, R2",
               diag_initial_last = "first", diag_no_diagnoses = TRUE,
               escalation_lab = "any"
               )
```
```{r}
# additional analyses regarding diagnoses
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = TRUE, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt in AUB-Fällen, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = TRUE, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt in AUB-Fällen, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = FALSE, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt in nicht-AUB-Fällen, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = FALSE, quarter.selection = 1:4, 
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "diag", research.question = 
                 "Welche Diagnosen wurden zuerst gestellt in nicht-AUB-Fällen, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
               )
for(q in seq(1, 4)){
  discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
                 remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
                 pandemic = "none", AUB = NA, quarter.selection = 1, 
                 month.selection=1:12, selected.years = "all",
                 dependent.variable = "diag", research.question =
                   paste0("Welche Diagnosen wurden zuerst gestellt in Q", q, 
                          ", R1"),
                 diag_initial_last = "first", diag_no_diagnoses = FALSE,
                 escalation_lab = "any"
                 )
  discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
                 remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
                 pandemic = "none", AUB = NA, quarter.selection = 1, 
                 month.selection=1:12, selected.years = "all",
                 dependent.variable = "diag", research.question =
                   paste0("Welche Diagnosen wurden zuerst gestellt in Q", q, 
                          ", R2"),
                 diag_initial_last = "first", diag_no_diagnoses = FALSE,
                 escalation_lab = "any"
                 )
}
```
```{r}
# analyses regarding age
discovery.tool(decision.rule = 1, agelims = c(1, 90), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "age", research.question = 
                 "Wie alt waren die Patienten, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
)
discovery.tool(decision.rule = 2, agelims = c(1, 90), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "age", research.question = 
                 "Wie alt waren die Patienten, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
)
discovery.tool(decision.rule = 1, agelims = c(18, 90), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "age", research.question = 
                 "Wie alt waren die Patienten (ohne Minderjährige), R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
)
discovery.tool(decision.rule = 2, agelims = c(18, 90), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "age", research.question = 
                 "Wie alt waren die Patienten (ohne Minderjährige), R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
)
discovery.tool(decision.rule = 1, agelims = c(18, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "age", research.question = 
                 "Wie alt waren die Patienten, ohne Minderjährige, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
)
discovery.tool(decision.rule = 2, agelims = c(18, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "age", research.question = 
                 "Wie alt waren die Patienten, ohne Minderjährige, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any"
)
```
```{r}
# analyses regarding time of escalation/ referral to specialist
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten zu einem Spezialisten geschickt, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "any"
)
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten zu einem Spezialisten geschickt, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "any"
)
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten zu einem Pneumologen geschickt, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "pulmonologist"
)
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten zu einem Pneumologen geschickt, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "pulmonologist"
)
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten zu einem Radiologen geschickt, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "radiologist"
)
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten zu einem Radiologen geschickt, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "radiologist"
)
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten in ein Krankenhaus geschickt, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "hospital"
)
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_ueberweis", research.question = 
                 "Wann wurden Patienten in ein Krankenhaus geschickt, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "hospital"
)
```
```{r}
# analyses regarding time of escalation/ time of lab test
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde (irgend-) ein Labortest angeordnet, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde (irgend-) ein Labortest angeordnet, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "any"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde auf C-reaktives Protein getestet, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "CRP"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde auf C-reaktives Protein getestet, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "CRP"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde auf Leukozyten getestet, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "leukocytes"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde auf Leukozyten getestet, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "leukocytes"
               )
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde auf Procalcitonin getestet, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "procalcitonin"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100),
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all",
               dependent.variable = "escalation_lab", research.question = 
                 "Wann wurde auf Procalcitonin getestet, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "procalcitonin"
               )
```
```{r}
# analyses regarding time of escalation/ time of antibiotics prescription
discovery.tool(decision.rule = 1, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100), 
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "escalation_antibiotics", 
               research.question = "Wann wurden Antibiotika verschrieben, R1",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "any"
               )
discovery.tool(decision.rule = 2, agelims = c(1, 150), insurance = "all",
               remove.copd = FALSE, lims.chronic.diseases = c(0, 100), 
               pandemic = "none", AUB = NA, quarter.selection = 1:4,
               month.selection=1:12, selected.years = "all", 
               dependent.variable = "escalation_antibiotics", 
               research.question = "Wann wurden Antibiotika verschrieben, R2",
               diag_initial_last = "first", diag_no_diagnoses = FALSE,
               escalation_lab = "any", escalation_ueberweis = "any"
               )
```