---
title: "Useful but not right now"
author: "Raphael Kroes, B.Sc."
date: "2023-10-25"
output: html_document
---

```{r}
episode.creating.fun<- function(ipc.data, add.data.list, i_diag=1, i_pzn=2, i_stamm=3, i_impf=4, i_labor=5, i_lu=6, i_ueberweis=7, start.time=0,length.of.episode,start.date="all",end.date="all", par.factor=1L){
  #a function which generates health incidents from the data. 
  #ipc.data is the data with IPC2 codes needed for finding the patients who had coughing (IPC2 code R05) as a symptom.
  #add.data.list is a list of data frames that are merged with the ipc data.
  #i_diag, i_pzn,  etc. are indicators which list element the diagnosis [pzn] data is (e.g. add.list.data[[x]]= diag.up => i_diag=x). If a dataset is to be excluded, set the respective indicator to NA.
  #start.time is the number of days before the patient went to their GP with coughing symptoms in which other health incidents may be recorded. It is currently redundand.
  #length.of.episode is the number of days after the patient went to their doctor for the first time that are analysed.
  #start.date is a specified TG_DateNum-value which marks the earliest date we want to analyse in the data, i.e. if we do not want to analyse all of the data but set a specific start date.
  #end.date is a specified TG_DateNum-value which marks the latest date we want to analyse in the data, i.e. if we do not want to analyse all of the data but set a specific end date.
  #par.factor is a factor that determines in how many chunks the data is separated in the process. Several functions scale (necessarily) in O(n^2), increasing par.factor might be able to speed up the process as the chunking up of the data set scales only in O(n).
  
  # error handles for function inputs
  if(all(sort(c(i_diag,i_pzn,i_stamm,i_impf,i_labor,i_lu,i_ueberweis))!=seq(1,length(add.data.list)))){
    stop("There is an error in the add.data.list or specification which data frame is where. The i_x variables should taken together create a sequence from 1 to the number of data frames in add.data.list. The function stops because this error would prove critical later on in the execution of the function.")
  }
  
  if(start.date!="all"){
    if(is.numeric(start.date)){
      if(start.date<min(as.numeric(ipc.data$TG_DateNum))) warning("Start date is earlier than the earliest incident in the dataset. The constraint is thus non-binding!")
    }else{
      stop("start date must be either 'all' or take a numeric value")
    }
  }
  
  if(end.date!="all"){
    if(is.numeric(end.date)){
      if(end.date>max(as.numeric(ipc.data$TG_DateNum))) warning("End date is later than the latest incident in the dataset. The constraint is thus non-binding!")
    }else{
      stop("End date must be either 'all' or take a numeric value")
    }
  }
  if(is.numeric(start.date) & is.numeric(end.date)){
    if(start.date>end.date) stop("The end date as entered into the function is before the start date.")
  }
  
  if(is.numeric(length.of.episode)){
    if(length.of.episode!=round(length.of.episode)) stop("length.of.episode must take an integer value!")
    if(length.of.episode>56) warning("length.of.episode is selected such that it looks at episodes more than 56 days after the patient went to their GP with cough for the first time. Beware that past these eight weeks we must consider that the cough is chronic. Also beware that the longer the time frame, the higher the likelihood that medically unconnected incidents are connected by this function.")
  }else{
    stop("length.of.episode must be numeric!")
  }
  

  # 1. step: enforce time limits
  # 1.1. enforce start date
  if(start.date!="all"){
    # 1.1.1. enforce start date for ipc.data
    ipc.data<- ipc.data[as.numeric(ipc.data$TG_DateNum)>=start.date,]
    if(nrow(ipc.data)==0) stop("There are no entries in ipc.data that correspond to this start.date request- after enforcing it, no rows were left!")
    
    # 1.1.2. enforce start date for all other data sets
    # ...for all other data sets
    rm.data.set<- c()
    for(i in seq(1,length(add.data.list))){
      ds<- add.data.list[[i]][as.numeric(add.data.list[[i]]$TG_DateNum)>=start.date,]
      if(nrow(ds)==0){
        rm.data.set<- c(rm.data.set,i)
      }else{
        add.data.list[[i]]<- ds
      }
    }
    if(length(rm.data.set)>1){
      warning(paste("Some data set(s) is/ are being dropped from the analysis because the start.date rule sets the number of rows in the corresponding dataset(s) to 0. Please have a look at the dataset(s) no°s",rm.data.set))
      add.data.list<- add.data.list[-rm.data.set]
    }
  }
  
  # 1.2. enforce end date
  if(end.date!="all"){
    # 1.1.1. enforce end date for ipc.data
    ipc.data<- ipc.data[as.numeric(ipc.data$TG_DateNum)<=end.date,]
    if(nrow(ipc.data)==0) stop("There are no entries in ipc.data that correspond to this end.date request- after enforcing it, no rows were left!")
    
    # 1.1.2. enforce end date for all other data sets
    # ...for all other data sets
    rm.data.set<- c()
    for(i in seq(1,length(add.data.list))){
      ds<- add.data.list[[i]][as.numeric(add.data.list[[i]]$TG_DateNum)<=end.date,]
      if(nrow(ds)==0){
        rm.data.set<- c(rm.data.set,i)
      }else{
        add.data.list[[i]]<- ds
      }
    }
    if(length(rm.data.set)>1){
      warning(paste("Some data set(s) is/ are being dropped from the analysis because the end.date rule sets the number of rows in the corresponding dataset(s) to 0. Please have a look at the dataset(s) no°s",rm.data.set))
      add.data.list<- add.data.list[-rm.data.set]
    }
  }
  
  
  
  # 2. step: filter out all patients who never coughed
  # ...for ipc.data
  cols<- seq(1,ncol(ipc.data))[grepl("ipc2", colnames(ipc.data))]
  selector.cough<- logical(nrow(ipc.data))
  for(i in seq(1,nrow(ipc.data))){
    ipc.string<- paste0(ipc.data[i,cols], collapse = "")
    selector.cough[i]<- grepl("R05",ipc.string)
  }
  
  patients.who.ever.coughed<- levels(as.factor(ipc.data$uniPatID[selector.cough]))
  ipc.data_2<- ipc.data[ipc.data$uniPatID %in% patients.who.ever.coughed,]

  #error handle: Are there any entries in the newly created data frame?
  if(nrow(ipc.data_2)==0) stop("There are no patients who ever coughed recorded in the dataset for this configuration.")
  
  # ...for all other data sets
  
  rm.data.set<- c()
  for(i in seq(1,length(add.data.list))){
    ds<- add.data.list[[i]]
    ds<-ds[ds$uniPatID %in% patients.who.ever.coughed,] #here
    if(nrow(ds)==0){
      rm.data.set<- c(rm.data.set,i)
    }else{
      add.data.list[[i]]<- ds
    }
  }
  if(length(rm.data.set)>1){
    warning(paste("Some data set(s) is/ are being dropped from the analysis because the patients in the dataset never went to their GP coughing. Please have a look at the dataset(s) no°s",rm.data.set))
    add.data.list<- add.data.list[-rm.data.set]
  }
  

  # 3. step: merge diagnosis data to ipc data
  no.cores<- detectCores()

  ipc.chunks<- chunk.data(ipc.data,no.cores*par.factor)
  diag.chunks<- list()
  dd<- add.data.list[[i_diag]]
  for (i in seq(1,no.cores*par.factor)) {
    patients<- ipc.chunks[[i]]$uniPatID
    diag.chunks[[i]]<- dd[dd$uniPatID %in% patients,]
  }
  rm(dd)
  
  # tic()
  # merger.cluster<- makeCluster(no.cores)
  # distinct.environment<- environment()
  # clusterExport(cl = merger.cluster, varlist = c("ipc.chunks","diag.chunks"), envir = distinct.environment)
  # merge_1<- parSapply(cl = merger.cluster, seq(1,no.cores*par.factor), function(i){
  #   ipc<- ipc.chunks[[i]]
  #   diag<- diag.chunks[[i]]
  # 
  #   ipc.id<- as.factor(paste(ipc$uniPatID, ipc$TG_DateNum))
  #   diag.id<- as.factor(paste(diag$uniPatID, diag$TG_DateNum))
  # 
  #   in.vec<- diag.id %in% ipc.id
  #   
  #   diag_2<- diag[,colnames(diag)!="uniPatID" & colnames(diag)!="TG_DateNum"]
  # 
  #   merge.matrix<- matrix(NA, nrow = nrow(ipc), ncol = ncol(ipc)+ncol(diag_2))
  #   merge.matrix[,1:ncol(ipc)]<- ipc
  #   for(j in seq(1,length(in.vec))){
  #     if(in.vec[j]){
  #       row<- which(ipc.id==diag.id[j])
  #       merge.matrix[row,seq(ncol(ipc)+1,ncol(merge.matrix))]<- diag_2[j,]
  #     }
  #   }
  #   return(merge.matrix)
  # })
  # stopCluster()
  
  # merge_1<- sapply(merge_1, rbind)
  # loop.time<- toc()
  # browser()
  # drop episodes with no diagnosis
  
  if(start.time==0){
    episode.cluster<- makeCluster(no.cores)
    distinct.environment<- environment()
    clusterExport(cl = episode.cluster, varlist = c("ipc.chunks","diag.chunks","length.of.episode"), envir = distinct.environment)
  episode_1<- parSapply(cl = episode.cluster, seq(1,no.cores*par.factor), function(i){
    ipc<- ipc.chunks[[i]]
    ipc$episode.id<- NA
    diag<- diag.chunks[[i]]
    #create episode matrix: patient, start date of incident, last diagnosis, number of diagnoses
    episode.matrix<- matrix(NA, nrow = nrow(ipc), ncol = 4)
    colnames(episode.matrix)<- c("uniPatID","TG_Start_Date","final_diagnosis","patient_did_cough")
    
    patients<- levels(ipc$uniPatID)
    
    for (j in seq(1,length(patients))) {
      sel.patient<- patients[j]
      entry.selection_ipc<- ipc$uniPatID==sel.patient
      entry.selection_diag<- diag$uniPatID==sel.patient
      dates.ipc<- ipc$TG_DateNum[entry.selection_ipc]
      dates.diag<- diag$TG_DateNum[entry.selection_diag]
      
      #select episodes when patient coughs
      
      
      d<- as.numeric(abs(diff(dates.sel.patient))>=length.of.episode)
      d_2<- 1+cumsum(d)
      d_3<- c(1,d_2)
      df$episode.id[entry.selection]<- as.factor(paste(sel.patient,d_3))
    }
    return(df)
  })
  stopCluster()
  episode_1<- sapply(episode_1,rbind)
  
  }else{
    #start.time!=0 what then?
  }
  browser()
  
  if(start.time==0){
    episode.chunks<- chunk.up(merge_1, no.cores*par.factor)
    episode.cluster<- makeCluster(no.cores)
    distinct.environment<- environment()
    clusterExport(cl = episode.cluster, varlist = c("episode.chunks","length.of.episode"), envir = distinct.environment)
  episode_1<- parSapply(cl = episode.cluster, seq(1,no.cores*par.factor), function(i){
    df<- episode.chunks[[i]]
    df$episode.id<- NA
    
    patients<- levels(df$uniPatID)
    for (j in seq(1,length(patients))) {
      sel.patient<- patients[j]
      entry.selection<- df$uniPatID==sel.patient
      dates.sel.patient<- df$TG_DateNum[entry.selection]
      d<- as.numeric(abs(diff(dates.sel.patient))>=length.of.episode)
      d_2<- 1+cumsum(d)
      d_3<- c(1,d_2)
      df$episode.id[entry.selection]<- as.factor(paste(sel.patient,d_3))
    }
    return(df)
  })
  stopCluster()
  episode_1<- sapply(episode_1,rbind)
  
  }else{
    #start.time!=0 what then?
  }
  
  #merge ipc with diag data, create episodes, select episodes that contain coughing, insert all into data frame, add all other information on the patients
}
```

```{r}
dl<- list(diag.up_2, pzn.up_2, stamm.up_2, impf.up, labor.up, lu.up, ueberweis.up)
```


```{r}
episode.creating.fun(ipc.data = ipc.up_2, 
                  add.data.list = dl,
                  length.of.episode = 56,
                  #start.date = (min(as.numeric(ipc.up_2$TG_DateNum))-100),
                  #start.date = (max(as.numeric(ipc.up_2$TG_DateNum))+110),
                  end.date = (max(as.numeric(ipc.up_2$TG_DateNum))+100))

#i_diag=1, i_pzn=2, i_stamm=3, i_impf=4, i_labor=5, i_lu=6, i_ueberweis=7
```



```{r}
boot.simple<- function(df, seed){
  set.seed(seed)
  n<- dim(df)[1]
  p<- dim(df)[2]
  out<- df
  out$uniPatID<- sample(out$uniPatID)
  out$TG_DateNum<- sample(out$TG_DateNum)
}
boot.ipc<- boot.simple(ipc.up_2,3434543)
boot.diag<- boot.simple(diag.up_2)

bootstrap.dag<- function(df, dag.from, dag.to){
  # Uses a directed acyclic graph to create a semiparametric bootstrap sample from the data.
  # df is the dataset to be sampled from
  # dag.from, dag.to are vectors. A number in either of these vectors corresponds to a vertex, the number corresponds to the column number. I.e. if there are three columns A, B, and C, 2 would be the vertex for B.
  # The function (1) identifies the independent variables and draws them randomly from the ECDF of corresponding the variable. Then, it finds the start point(s) of the graph
  n<- nrow(df)
  
}

```



```{r}
no.overlaps<- numeric(nrow(episodes))
no.overlaps[1]<- NA
for(i in seq(2,nrow(episodes))){
  if(episodes$uniPatID[i]==episodes$uniPatID[i-1]){
    no.overlaps[i]<- episodes$end_date[i-1]>episodes$start_date[i]
  }else{
    no.overlaps[i]<- NA
  }
}
```


```{r}
episodes_6months<- episode.fun(ipc.up_2, 175)
no.overlaps_6months<- numeric(nrow(episodes_6months))
no.overlaps_6months[1]<- NA
for(i in seq(2,nrow(episodes_6months))){
  if(episodes_6months$uniPatID[i]==episodes_6months$uniPatID[i-1]){
    no.overlaps_6months[i]<- episodes_6months$end_date[i-1] > episodes_6months$start_date[i]
  }else{
    no.overlaps_6months[i]<- NA
  }
}
sum(no.overlaps_6months, na.rm = TRUE)
```

```{r}
aligner.parallel<- function(df, x, no.splits, no.cores=detectCores()-1){
  chunked.df<- chunk.data(df, no.splits)
  align.cluster<- makeCluster(no.cores)
  distinct_env<- environment()
  clusterExport(cl = align.cluster, varlist = c("chunked.df","aligner","x"), envir = distinct_env)
  result.list<- parSapply(cl = align.cluster, seq_along(chunked.df), FUN = function(i){
    df_i<- chunked.df[[i]]
    return(aligner(chunked.df,x))
  })
  stopCluster(align.cluster)
  browser()
  out<- sapply(result.list,rbind)
  return(out)
}
```

```{r}
latest.entry.selector<- function(problemdata){
  # For data sets which contain multiple entries for identical patient/ date combinations. Selects the newest entry of the multiple episodes and removes the other one(s).
  problemdata<- problemdata|>
    arrange(TG_DateNum)
  ids<- levels(as.factor(problemdata$uniPatID))
  out<- as.data.frame(matrix(NA,nrow = length(ids), ncol = ncol(problemdata)))
  colnames(out)<- colnames(problemdata)
  int.pb<- txtProgressBar(1,length(ids))  
  for(i in seq_along(ids)){
    setTxtProgressBar(int.pb,i)
    loc<- max(which(problemdata$uniPatID==ids[i]))
    out[i,]<- problemdata[loc,]
  }
  return(out)
}
```

```{r}
summary.plots<- function(episodedf,name.prefix){
  #function to create plots based on an episode data frame episodedf. name.prefix is a character string used to make the names of the plots distinguishable. 
  earliest.TG_Date<- min(episodedf$start_date)
  latest.TG_Date<- max(episodedf$start_date)
  earliest.year.POSIXlt<- year(TG_DateNum2date(earliest.TG_Date))
  latest.year.POSIXlt<- year(TG_DateNum2date(latest.TG_Date))
  no.years<- latest.year.POSIXlt-earliest.year.POSIXlt
  pandemic.start<- date2TG_DateNum("2020-01-01")
  pandemic.end<- date2TG_DateNum("2023-01-01")
  before.pandemic<- episodedf[episodedf$start_date<pandemic.start,]
  only.pandemic<- episodedf[episodedf$start_date>=pandemic.start & episodedf$start_date<pandemic.end,]
  length.pandemic<- 3
  browser()
  
  #distribution of diagnosis
  #1. collect all final diagnoses
  all.diagnoses<- as.vector(as.matrix(episodedf[,grepl("last_icd10", colnames(episodedf))]))
  all.diagnoses<- all.diagnoses[!is.na(all.diagnoses)]
  all.diagnoses<- all.diagnoses[all.diagnoses!="0"]
  
  chapters<- icd10.to.chapter(all.diagnoses)[,2]
  im<- table(chapters)
  chapter.no<- as.numeric(names(im))
  names(im)<- NULL
  prob<- numeric(22)
  prob[chapter.no]<- im
  prob<- prob/sum(prob)
  d.chapter<- data.frame(x=1:22,prob=prob)

  
  blocks<- icd10.to.block(all.diagnoses)
  im<- table(blocks[,1])
  blocks.no<- as.numeric(names(im))
  names(im)<- NULL
  prob<- numeric(241)
  prob[blocks.no]<- im
  prob<- prob/sum(prob)
  d.block_num<- data.frame(x=1:241,prob=prob)
  d.block_description<- data.frame(x=icd10_blocks$description, prob=prob)
  
  p<- ggplot(d.chapter, aes(x=x, y=prob)) +
    geom_bar(stat = "identity", fill="skyblue") +
    labs(title = "What diagnoses did the GPs settle on?",x = "ICD10 chapter", y= "percentage")
  ggsave(paste0(name.prefix,"diagnoses_chapter.png"), plot = p, path = getwd(), device = "png")

  p<- ggplot(d.block_num, aes(x=x, y=prob)) +
    geom_bar(stat = "identity", fill="skyblue") +
    labs(title = "What diagnoses did the GPs settle on?",x = "ICD10 block", y= "percentage")
  ggsave(paste0(name.prefix,"diagnoses_block_num.png"), plot = p, path = getwd(), device = "png")

  p<- ggplot(d.block_description, aes(x=x, y=prob)) +
    geom_bar(stat = "identity", fill="skyblue") +
    labs(title = "What diagnoses did the GPs settle on?",x = "ICD10 block", y= "percentage")
  ggsave(paste0(name.prefix,"diagnoses_block_description.png"), plot = p, path = getwd(), device = "png")

  write_xlsx(data.frame(no=1:241,description=icd10_blocks$description, probability=prob),"diag.xlsx")
  
  # #no visits
  # x<-  table(table(episodedf$uniPatID))
  # im_1<- seq(max(x),1)
  # im_2<- numeric(length(im_1))
  # for(i in seq_along(im_1)){
  #   im_3<- as.character(im_1[i])
  #   im_2[i]<- x[names(x)==im_3]
  # }
  # im_2<-  im_2/sum(im_2)
  # d<- data.frame(x=im_1, prob=im_2)
  # 
  # 
  # max.visits<- max(episodedf$uniPatID)
  # no.quarters<- no.years*4
  # x<- matrix(0,nrow = max.visits,ncol = no.quarters)
  # #find how often per quarter people went to their GP
  # 
  # 
  # p<- ggplot(d, aes(x=x,y=prob)) +
  #   geom_bar(stat = "identity", fill="skyblue") +
  #   labs(title = paste("The patients visited the GP clinic x times across", no.years*4, "quarters"),x = "number of visits", y= "Percentage")
  # 
  # ggsave(paste0(name.prefix,"no_visits.png"), plot = p, path = getwd(), device = "png")

  #age
  im_1<- as.numeric(year(TG_DateNum2date(episodedf$start_date)))
  im_2<- episodedf$Geburtsjahr
  im_3<- numeric(length(im_1))
  for(i in seq(1,length(im_1))){
    im_3[i]<- im_1[i]-im_2[i]
  }
  im_3<- im_3[!is.na(im_3)]
  x<- as.numeric(year(TG_DateNum2date(episodedf$start_date)))-episodedf$Geburtsjahr
  if(sum(is.na(x))>0){
    warning(paste("There are",sum(is.na(x)),"entries where no birth date is available. This corresponds to",round(sum(is.na(x))/length(x),2)*100), "% of all entries. The NA results are dropped in the following.")
    x<- x[!is.na(x)]
  }
  max.age<- max(c(100,max(x)))
  im<- table(x)
  ages<- as.numeric(names(im))
  names(im)<- NULL
  prob<- numeric(max.age)
  prob[ages]<- im
  prob<- prob/sum(prob)
  d<- data.frame(x=seq(1,max.age),prob=prob)

  y<- age.weights(1,max.age)
  d$y<- y
  # p <- ggplot(d, aes(x = x, y = prob)) +
  #     geom_bar(stat = "identity", fill = "skyblue") +
  #     geom_line(aes(y = y), color = "red") +
  #     scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  #     scale_y_continuous(labels = scales::percent_format()) +
  #     labs(title = "How old were the patients who had cough?",
  #          x = "Age in years",
  #          y = "Percentage")
  
  #ChatGPT.1
  # p <- ggplot(d, aes(x = x, y = prob, fill = "Bars", color = "Line")) +
  #   geom_bar(stat = "identity") +
  #   geom_line(aes(y = y)) +
  #   scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  #   scale_y_continuous(labels = scales::percent_format()) +
  #   labs(title = "How old were the patients who had cough?",
  #        x = "Age in years",
  #        y = "Percentage",
  #        fill = "Legend Title") +
  #   theme(legend.position = "bottom")
  # p <- ggplot(d, aes(x = x, y = prob)) +
  #     geom_bar(stat = "identity", fill = "skyblue", aes(fill = "Bar")) +
  #     geom_line(aes(y = y, color = "Line")) +
  #     scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  #     scale_y_continuous(labels = scales::percent_format()) +
  #     labs(title = "How old were the patients who had cough?",
  #          x = "Age in years",
  #          y = "Percentage") +
  #     scale_fill_manual(name = "Legend", values = c("Bar" = "skyblue")) #+
  #     #scale_color_manual(name = "Legend", values = c("Line" = "red"), guide = guide_legend(override.aes = list(linetype = c("dashed"))))
  
  # p<- ggplot(d, aes(x=x, y=prob)) +
  #   geom_bar(stat = "identity",fill = "skyblue") +
  #   geom_line(aes(y=y, color = "red")) +
  #   scale_x_continuous(breaks = seq(0,100,by=5)) +
  #   scale_y_continuous(labels = scales::percent_format()) +
  #   labs(title = "How old were the patients who had cough?",
  #          x = "Age in years",
  #          y = "Percentage") +
  #   scale_fill_manual(name = "")
  # p<- ggplot(d, aes(x = x, y = prob)) +
  # geom_bar(stat = "identity", fill = "skyblue", aes(fill = "Patient age")) +
  # geom_line(aes(y = y, color = "Age distribution in Germany")) +
  # scale_x_continuous(breaks = seq(0,100,by=5)) +
  # scale_y_continuous(labels = scales::percent_format()) +
  # labs(title = "How old were the patients who had cough?",
  #        x = "Age in years",
  #        y = "Percentage") +
  # scale_color_manual(name= "Explanation",
  #                    breaks = c("Patient age","Age distribution in Germany"),
  #                    values = c("Patient age"="skyblue","Age distribution in Germany"="red")) +
  # theme(legend.position = "bottom")

  p<- ggplot(d, aes(x = x)) +
    geom_bar(aes(y = prob, fill = "Patient age"), stat = "identity") +
    geom_line(aes(y = y, color = "Age distribution of Germany")) +
    labs(title = "How old were the patients who had cough?",
            x = "Age in years",
            y = "Percentage") +
    scale_fill_manual(values = c("skyblue"), labels = c("Patient age")) +
    scale_color_manual(values = c("red"), labels = c("Age distribution of Germany")) +
    theme(legend.position = "bottom")

  ggsave(paste0(name.prefix,"age.png"), plot = p, path = getwd(), device = "png")

  #age with/out pandemic
  x<- as.numeric(year(TG_DateNum2date(before.pandemic$start_date)))-before.pandemic$Geburtsjahr
  if(sum(is.na(x))>0){
    warning(paste("There are",sum(is.na(x)),"entries where no birth date is available. This corresponds to",round(sum(is.na(x))/length(x),2)*100), "% of all entries. The NA results are dropped in the following.")
    x<- x[!is.na(x)]
  }
  im<- table(x)
  ages<- as.numeric(names(im))
  names(im)<- NULL
  prob<- numeric(max.age)
  prob[ages]<- im
  prob<- prob/sum(prob)
  d<- data.frame(x=seq(1,max.age),prob=prob)

  y<- age.weights(1,max.age)
  d$y<- y
  p<- ggplot(d, aes(x = x)) +
    geom_bar(aes(y = prob, fill = "Patient age"), stat = "identity") +
    geom_line(aes(y = y, color = "Age distribution of Germany")) +
    labs(title = "How old were the patients who had cough?",
            x = "Age in years",
            y = "Percentage") +
    scale_fill_manual(values = c("skyblue"), labels = c("Patient age")) +
    scale_color_manual(values = c("red"), labels = c("Age distribution of Germany")) +
    theme(legend.position = "bottom")

  ggsave(paste0(name.prefix,"age_before_pandemic.png"), plot = p, path = getwd(), device = "png")

  x<- as.numeric(year(TG_DateNum2date(only.pandemic$start_date)))-only.pandemic$Geburtsjahr
  if(sum(is.na(x))>0){
    warning(paste("There are",sum(is.na(x)),"entries where no birth date is available. This corresponds to",round(sum(is.na(x))/length(x),2)*100), "% of all entries. The NA results are dropped in the following.")
    x<- x[!is.na(x)]
  }
  im<- table(x)
  ages<- as.numeric(names(im))
  names(im)<- NULL
  prob<- numeric(max.age)
  prob[ages]<- im
  prob<- prob/sum(prob)
  d<- data.frame(x=seq(1,max.age),prob=prob)

  y<- age.weights(1,max.age)
  d$y<- y
  p<- ggplot(d, aes(x = x)) +
    geom_bar(aes(y = prob, fill = "Patient age"), stat = "identity") +
    geom_line(aes(y = y, color = "Age distribution of Germany")) +
    labs(title = "How old were the patients who had cough?",
            x = "Age in years",
            y = "Percentage") +
    scale_fill_manual(values = c("skyblue"), labels = c("Patient age")) +
    scale_color_manual(values = c("red"), labels = c("Age distribution of Germany")) +
    theme(legend.position = "bottom")

  ggsave(paste0(name.prefix,"age_only_pandemic.png"), plot = p, path = getwd(), device = "png")
  
  #no. visits with/out pandemic
  before.pandemic<- episodedf[episodedf$start_date<pandemic.start,]
  only.pandemic<- episodedf[episodedf$start_date>=pandemic.start & episodedf$start_date<pandemic.end,]
  length.pandemic<- 3
  
  x<- round(as.vector((table(before.pandemic$uniPatID)/(no.years-length.pandemic))),3)#change to correct no of years, and make it annual
  d<- as.data.frame(table(x))
  p<- ggplot(d, aes(x=x,y=Freq)) +
    geom_bar(stat = "identity", fill="skyblue") +
    labs(title = "How often did patients attend their GP before the pandemic?",x = "Number of visits per year", y= "percentage")
  
  ggsave(paste0(name.prefix,"no_visits_before_pandemic.png"), plot = p, path = getwd(), device = "png")
  
  x<- round(as.vector((table(only.pandemic$uniPatID)/no.years)),3)#change to correct no of years, and make it annual
  d<- as.data.frame(table(x))
  p<- ggplot(d, aes(x=x,y=Freq)) +
    geom_bar(stat = "identity", fill="skyblue") +
    labs(title = "How often did patients attend their GP during the pandemic?",x = "Number of visits per year", y= "percentage")
  
  ggsave(paste0(name.prefix,"no_visits_during_pandemic.png"), plot = p, path = getwd(), device = "png")
  

  
}
summary.plots(full.data.episodes_r1,"dr1_")
#age is buggy. This is due to incorrect stammdata. Some uniPatIDs are not unique!

codes<- c(icd10_blocks$start_code,icd10_blocks$end_code)

icd10.to.block(codes[135:140])
#percentage + plot chronisch (copd, asthma)
#plot: distr. of diagnosis
#plot: distr. of diagnosis cond. on treatment (lufu, xray, lab)
#make visits quarterly
#wann eskaliert die therapie zeitlich
#
#
#Plan today: 
#1. Add data to episodedfs
#1b do decision rules 3-5 work?
#2. new summary stats
#3. new summary plots
```

